### ISSUE TITLE
_onRemove not working

### ISSUE THREAD

**Issue by skuderos** [dagjomar/Leaflet.ParallaxMarker#8]
Hey there! I'm using this plugin to simulate altitude on aircraft markers and it works quite nicely, until I delete a marker. It appears some of the event listeners don't get removed correctly. I tracked it down to line 22 in the .js file. The following line needs to be added to correctly handle zoom events after deleting an object: 

this._map.off('zoomstart', this._onZoomStart, this);

**Comment by dagjomar** [comment]
Hi!
I commited this now. Thanks 👍
